# Generated by Django 3.2.6 on 2021-08-24 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.PositiveSmallIntegerField(choices=[(1, 'Saipa Motmaen'), (2, 'Iran Khodro'), (3, 'Hyundai')], default=1, verbose_name='Brand')),
                ('name', models.SlugField(verbose_name='Name')),
                ('color', models.CharField(blank=True, max_length=10, verbose_name='Color')),
                ('price', models.IntegerField(help_text='In Tomans', validators=[django.core.validators.MinValueValidator(10000000)], verbose_name='Price')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Is Enable')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
