# Generated by Django 3.2.6 on 2021-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Saipa'), (2, 'Iran Khodro'), (3, 'Hyundai')], default=1, verbose_name='Brand'),
        ),
    ]
