# Generated by Django 3.2.6 on 2021-08-29 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rent', '0002_alter_car_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('rent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('is_enable', models.BooleanField(default=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rent.car', verbose_name='car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='user')),
            ],
        ),
    ]
