# Generated by Django 3.2.6 on 2021-08-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20210829_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.car', verbose_name='car'),
        ),
    ]
