# Generated by Django 3.2.6 on 2021-08-29 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rent', '0007_alter_carrent_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='user'),
        ),
    ]
