# Generated by Django 3.2.6 on 2021-08-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rent', '0008_alter_carrent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrent',
            old_name='end_rent_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='carrent',
            old_name='start_rent_time',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='carrent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.car', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='carrent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile', verbose_name='user'),
        ),
    ]
